### ISSUE TITLE
결과화면 공유하기 네비게이션 바 버튼으로 이동 - Level 1

### ISSUE THREAD

**Issue by gaeng2y** [Swift-Coding-Club/Level1Kuiz#63]

**Comment by Dtzer0** [comment]
현재 공유하기 버튼이 이런식으로 보기 불편하게 설정되어있습니다.
<img src="https://github.com/Swift-Coding-Club/Level1Kuiz/assets/66416524/56ca48ce-1d2e-40bc-b2a2-fb088a8e1312.png"  width="200" height="414">

해당 공유하기 버튼이 내비게이션 바 버튼을 사용해서 우측 상단에 아이콘으로 위치했으면 합니다.
* 해당 노랑 영역에는 다시하기 버튼만 존재해야합니다!!
